import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Application",
    projects: [
        "Projects/OZeon",
        "Projects/Modules/DataKit",
        "Projects/Modules/DomainKit",
        "Projects/Modules/CoreKit",
        "Projects/Modules/NetworkKit",
        "Projects/Modules/DesignSystemKit",
        "Projects/Modules/PresentationKit",
        "Projects/Modules/ThirdPartyManager"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
