opt_in_rules:
  - sorted_imports

disabled_rules:
  - trailing_whitespace
  - function_body_length
  - identifier_name
  - type_name
  - multiple_closures_with_trailing_closure

excluded:
  - Derived
  - Plugins
  - Project.swift
  - Tuist